
import {
  Bot,
  User,
  Users,
  Target,
  Flag,
  Star,
  Heart,
  Award,
  Bookmark,
  Lightbulb,
  Monitor,
  Server,
  Database,
  Cpu,
  Code,
  Terminal,
  Key,
  Shield,
  UserCog,
} from 'lucide-react';

// Icon options for agent
export const iconOptions = [
  { name: 'Bot', component: Bot },
  { name: 'User', component: User },
  { name: 'Users', component: Users },
  { name: 'Target', component: Target },
  { name: 'Flag', component: Flag },
  { name: 'Star', component: Star },
  { name: 'Heart', component: Heart },
  { name: 'Award', component: Award },
  { name: 'Bookmark', component: Bookmark },
  { name: 'Lightbulb', component: Lightbulb },
  { name: 'Monitor', component: Monitor },
  { name: 'Server', component: Server },
  { name: 'Database', component: Database },
  { name: 'CPU', component: Cpu },
  { name: 'Code', component: Code },
  { name: 'Terminal', component: Terminal },
  { name: 'Key', component: Key },
  { name: 'Shield', component: Shield },
  { name: 'UserCog', component: UserCog },
  { name: 'Default', component: Bot },
];
